INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('Mercedes', 'S500', '5', '5000', 2004);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('Mercedes', 'GLA', '5', '5000', 2004);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('Mercedes', 'S600', '5', '5000', 2004);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('BMW', 'E65', '5', '7000', 2004);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('BMW', 'F39', '5', '7000', 2004);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('Ford', 'Focus', '5', '3500', 2004);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('Ford', 'Fiesta', '5', '3500', 2004);

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('John', 'Doe', 'johndoe@gmail.com', 'United States', '12 Brooklying Bride Park', 'NY', '1-(123) 333-1231');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('John', 'Nelson', 'johnnelson@gmail.com', 'United States', '12 Brooklying Bride Park', 'NY', '1-(124) 444-1231');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('John', 'Stevenson', 'johnstvn@gmail.com', 'United States', '12 Brooklying Bride Park', 'NY', '1-(125) 555-1231');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('Carl', 'Carlson', 'johncarl@gmail.com', 'United States', '12 Brooklying Bride Park', 'NY', '1-(126) 666-1231');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('Carl', 'Amit', 'carlamite@gmail.com', 'Germany', '12 Brooklying Bride Park', 'Berlin', '1-(127) 777-1231');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('Anna', 'Rojas', 'annarojas@gmail.com', 'Mexico', '12 Brooklying Bride Park', 'Guadalajara', '1-(128) 888-1231');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('Alex', 'Smith', 'alexsmith@gmail.com', 'United Kingdom', '12 Brooklying Bride Park', 'London', '1-(129) 999-1231');

INSERT INTO RESERVATION (VEHICLE_ID, CLIENT_ID, RESERVATION_DATE) VALUES ((SELECT VEHICLE_ID FROM VEHICLE WHERE VEHICLE_MODEL = 'S500'), (SELECT CLIENT_ID FROM CLIENT WHERE LAST_NAME = 'Doe'), '2020-12-01');